name: Sync configuration files

on:
  schedule:
    - cron:  "0 0 * * *"
  push:
    branches:
      - 'master'
      - 'ci/configs-sync'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check and update the Bee version
        uses: ethersphere/repo-sync-action@v1
        with:
          repo: ethersphere/configs-js
          token: ${{ secrets.REPO_GHA_PAT }}
          author: bee-worker <bee-worker@ethswarm.org>
